name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v4
        with:
          arguments: '--list --mode diff-ref=origin/main'
