name: Publish 1.1 docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    name: Publish 1.1 Docs
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java 8
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 8

      - name: Install sbt
        uses: sbt/setup-sbt@a627500d27445f8c5021755a439829b6e78e3358 # v1.1.15

      - name: Install Graphviz
        run: |-
          sudo apt-get install graphviz

      - name: Build 1.1.x Documentation
        run: |-
          sbt "set ThisBuild / version := \"1.1.0\"; docs/paradox; unidoc"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create 1.1.x directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-persistence-r2dbc/1.1.0/
          mkdir -p target/nightly-docs/docs/pekko-persistence-r2dbc/1.1/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-r2dbc/1.1.0/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-r2dbc/1.1/docs
          rm -r docs/target/paradox/site/main/
          cp -r docs/target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-r2dbc/1.1.0/api
          cp -r docs/target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-r2dbc/1.1/api
          rm -r docs/target/scala-2.13/unidoc

      - name: Upload 1.1.x docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-r2dbc/1.1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.1 docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-r2dbc/1.1 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
